<InterfaceChat>:
    id: tela_usuario
    orientation: 'vertical'

	BoxLayout:
        id: grid_superior
        orientation: 'horizontal'

        ScrollView:
			id: historico_mensagens

            BoxLayout:
                id: mensagens
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height

                Label:
                    id: historico
                    text: 'oi'
                    font_size: 20
                    size_hint_y: None
                    height: 20

                Label:
                    id: historico
                    text: 'tudo bem?'
                    font_size: 20
                    size_hint_y: None
                    height: 20
                Label:
                    id: historico
                    text: 'como vai vc'
                    font_size: 20
                    size_hint_y: None
                    height: 20

                Label:
                    id: historico
                    text: 'ieeeei'
                    font_size: 20
                    size_hint_y: None
                    height: 20

                Label:
                    id: historico
                    text: 'lascou'
                    font_size: 20
                    size_hint_y: None
                    height: 20

        BoxLayout:
			id: grid_usuarios_topicos
			orientation: 'vertical'

			BoxLayout:
                id: box_usuarios
                orientation: 'vertical'

                Label:
                    id: label_usuarios
                    text: 'Lista de usuários'
                    font_size: 20

                ScrollView:
                    id: scroll_usuarios

                    BoxLayout:
                        id: lista_usuarios
                        orientation: 'vertical'
                        size_hint_y: None
                        height: self.minimum_height

                        Button:
                            id: usuario_1
                            text: 'teste 1'
                            font_size: 20
                            size_hint_y: None
                            height: 100
                        Button:
                            id: usuario_2
                            text: 'teste 2'
                            font_size: 20
                            size_hint_y: None
                            height: 100

                        Button:
                            id: usuario_3
                            text: 'teste 3'
                            font_size: 20
                            size_hint_y: None
                            height: 100

                        Button:
                            id: usuario_4
                            text: 'teste 4'
                            font_size: 20
                            size_hint_y: None
                            height: 100

			BoxLayout:
                id: box_topicos
                orientation: 'vertical'

                Label:
                    id: label_topicos
                    text: 'Lista de tópicos'
                    font_size: 20

                ScrollView:
                    id: scroll_topicos

                    BoxLayout:
                        id: lista_topicos
                        orientation: 'vertical'
                        size_hint_y: None
                        height: self.minimum_height

                        Button:
                            id: topico_1
                            text: 'nba'
                            font_size: 20
                            size_hint_y: None
                            height: 100

                        Button:
                            id: topico_2
                            text: 'nfl'
                            font_size: 20
                            size_hint_y: None
                            height: 100

                        Button:
                            id: topico_3
                            text: 'nbb'
                            font_size: 20
                            size_hint_y: None
                            height: 100

                        Button:
                            id: topico_4
                            text: 'mlb'
                            font_size: 20
                            size_hint_y: None
                            height: 100

    BoxLayout:
        id: grid_inferior
        orientation: 'vertical'
		size_hint_y: None
		height: 100

        BoxLayout:
            id: grid_mensagem_usuario
            orientation: 'horizontal'
            size_hint_y: None
            height: 50

            TextInput:
                id: text_input_mensagem_usuario
                text: 'Digite algo...'
                font_size: 20

            Button:
                id: botao_enviar
                text: 'Enviar mensagem para usuário'
                font_size: 20

        BoxLayout:
            id: grid_mensagem_topico
            orientation: 'horizontal'
            size_hint_y: None
            height: 50

            TextInput:
                id: text_input_mensagem_topico
                text: 'Digite algo...'
                font_size: 20

            Button:
                id: botao_enviar
                text: 'Enviar mensagem para o tópico'
                font_size: 20
